FROM python:3.10

WORKDIR /

RUN sudo apt-get install cmake

RUN wget https://files.pythonhosted.org/packages/05/57/e8a8caa3c89a27f80bc78da39c423e2553f482a3705adc619176a3a24b36/dlib-19.17.0.tar.gz

RUN tar -xvzf dlib-19.17.0.tar.gz

RUN cd dlib-19.17.0/

RUN sudo python3 setup.py install

WORKDIR /

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8001

CMD ["uvicorn", "src.fastapiApp:app", "--host", "0.0.0.0", "--port", "8001"]