FROM python:3.10

WORKDIR /

# Устанавливаем необходимые системные зависимости
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    libopenblas-dev \
    libatlas-base-dev \
    libboost-python-dev \
    && rm -rf /var/lib/apt/lists/*

# Устанавливаем pip и обновляем его
RUN pip install --upgrade pip

# Устанавливаем dlib и cmake
RUN pip install cmake dlib

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8001

CMD ["uvicorn", "src.fastapiApp:app", "--host", "0.0.0.0", "--port", "8001"]